- hosts: all
  become: true
  collections:
    - kubernetes.core
  tasks:
    - name: Create Kubernetes secret
      k8s:
        kubeconfig: "/home/dew/.kube/config"
        definition: "{{ lookup('file', '/home/dew/Secret.yml') | from_yaml }}"
      environment:
        KUBECONFIG: "/home/dew/.kube/config"

    - name: Create new deployment
      k8s:
        kubeconfig: "/home/dew/.kube/config"
        definition: "{{ lookup('file', '/home/dew/Deployment.yml') | from_yaml }}"

    - name: Create new service
      k8s:
        kubeconfig: "/home/dew/.kube/config"
        definition: "{{ lookup('file', '/home/dew/Service.yml') | from_yaml }}"
